export default [
    { size: '5mb', numberOfDeps: 1, depth: 0, outputDir: '1-0' },
    { size: '5mb', numberOfDeps: 2, depth: 0, outputDir: '2-0' },
    { size: '5mb', numberOfDeps: 2, depth: 1, outputDir: '2-1' },
    { size: '5mb', numberOfDeps: 2, depth: 2, outputDir: '2-2' },
    { size: '5mb', numberOfDeps: 2, depth: 3, outputDir: '2-3' },
    { size: '5mb', numberOfDeps: 2, depth: 4, outputDir: '2-4' },
    { size: '5mb', numberOfDeps: 3, depth: 0, outputDir: '3-0' },
    { size: '5mb', numberOfDeps: 3, depth: 1, outputDir: '3-1' },
    { size: '5mb', numberOfDeps: 3, depth: 2, outputDir: '3-2' },
    { size: '5mb', numberOfDeps: 3, depth: 3, outputDir: '3-3' },
    { size: '5mb', numberOfDeps: 5, depth: 0, outputDir: '5-0' },
    { size: '5mb', numberOfDeps: 5, depth: 1, outputDir: '5-1' },
    { size: '5mb', numberOfDeps: 5, depth: 2, outputDir: '5-2' },
    { size: '5mb', numberOfDeps: 10, depth: 0, outputDir: '10-0' },
    { size: '5mb', numberOfDeps: 10, depth: 1, outputDir: '10-1' },
    { size: '5mb', numberOfDeps: 20, depth: 0, outputDir: '20-0' },
    { size: '5mb', numberOfDeps: 50, depth: 0, outputDir: '50-0' },
    { size: '5mb', numberOfDeps: 100, depth: 0, outputDir: '100-0' },
    { size: '5mb', numberOfDeps: 200, depth: 0, outputDir: '200-0' },
];